// Scratch caller-leg peer for #50. Not shipped; nothing here survives into the
// phone-test tool (#51) except what it proves. It is the other half of a self-call:
// the bridge's number dials itself, the caller leg runs <Connect><ConversationRelay>
// pointed here, and this process is "the operator" — it hears what the bridge's leg
// says as `prompt` text, speaks with `text` tokens, keys digits, and hangs up, all
// driven over a localhost control port. Every frame is recorded in the spike's
// format so redact.ts can turn a run into a fixture.
//
// Run from the repo root (Funnel routing a path of the shared public host here):
//   mise exec -- bun spikes/conversationrelay/operator.ts
// See README.md beside this file.

import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { appendFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ServerWebSocket } from "bun";

const env = (name: string, fallback?: string): string => {
  const v = process.env[name] ?? fallback;
  if (v === undefined) throw new Error(`${name} is required`);
  return v;
};

const PUBLIC_PORT = Number(env("OP_PORT", "8797"));
const CONTROL_PORT = Number(env("OP_CONTROL_PORT", "8796"));
const BASE_URL = env("THICKET_PUBLIC_BASE_URL").replace(/\/$/, "");
// The path Funnel routes to this process on the shared public host; the bridge owns /.
const PREFIX = env("OP_PATH_PREFIX", "/operator");
const AUTH_TOKEN = env("TWILIO_AUTH_TOKEN");
const ACCOUNT = env("TWILIO_ACCOUNT_SID");
const KEY = env("TWILIO_API_KEY_SID");
const SECRET = env("TWILIO_API_KEY_SECRET");
const NUMBER = env("TWILIO_PHONE_NUMBER");
const PIN = process.env.THICKET_PHONE_PIN; // never recorded; see record()
const STATE_DIR = env("SPIKE_STATE", join(homedir(), "thicket-test", "spike-cr"));
// The caller leg's TwiML is generated by this same process, so the secret needs no
// coordination with anything: fresh every boot.
const RELAY_SECRET = randomBytes(12).toString("hex");
const RECORDINGS = join(STATE_DIR, "recordings");
mkdirSync(RECORDINGS, { recursive: true });

const PUBLIC_HOST = new URL(BASE_URL).host;
const RELAY_URL = `wss://${PUBLIC_HOST}${PREFIX}/relay/${RELAY_SECRET}`;

// ---------------------------------------------------------------- recording

type Entry = Record<string, unknown>;
const started = Date.now();

function record(callSid: string | undefined, entry: Entry): void {
  let line = JSON.stringify({ t: new Date().toISOString(), ms: Date.now() - started, ...entry });
  // The PIN must never reach a log or a recording, whatever path it took to get here.
  if (PIN !== undefined) line = line.replaceAll(PIN, "«8 digits»");
  console.log(line);
  const file = callSid ? `${callSid}.op.jsonl` : "_operator.jsonl";
  appendFileSync(join(RECORDINGS, file), line + "\n");
}

// ---------------------------------------------------------------- signature

function signature(url: string, params: URLSearchParams | undefined): string {
  let data = url;
  if (params) {
    for (const key of [...params.keys()].sort()) data += key + params.get(key);
  }
  return createHmac("sha1", AUTH_TOKEN).update(data).digest("base64");
}

function signatureMatches(expected: string, header: string | null): boolean {
  if (!header) return false;
  const a = Buffer.from(expected);
  const b = Buffer.from(header);
  return a.length === b.length && timingSafeEqual(a, b);
}

// The URL Twilio signed is the one it was given — prefix included. What arrives here
// depends on whether Funnel strips the mount path, which this spike records rather
// than assumes: candidates are computed for the path as requested and, when the
// prefix was stripped on the way in, for the path with it restored.
function signatureCandidates(req: Request, header: string | null): Record<string, boolean> {
  const u = new URL(req.url);
  const paths = new Set([u.pathname, u.pathname.startsWith(PREFIX) ? u.pathname : PREFIX + u.pathname]);
  const matched: Record<string, boolean> = {};
  for (const path of paths) {
    for (const scheme of ["wss", "https"]) {
      matched[`${scheme}://${PUBLIC_HOST}${path}`] = signatureMatches(signature(`${scheme}://${PUBLIC_HOST}${path}${u.search}`, undefined), header);
    }
  }
  return matched;
}

// ---------------------------------------------------------------- call state

interface Call {
  callSid: string;
  ws: ServerWebSocket<Conn>;
  setupAt: number;
}

interface Conn {
  id: string;
  callSid?: string;
  buffered: Entry[];
}

let current: Call | undefined;
let restSid: string | undefined; // the SID REST returned for the leg we placed
const transcript: Array<Record<string, unknown>> = [];

function note(who: "heard" | "said" | "keyed" | "event", text: string): void {
  transcript.push({ ms: Date.now() - started, [who]: text });
}

// ---------------------------------------------------------------- TwiML & REST

function escapeXml(s: string): string {
  return s.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[c]!);
}

// The caller leg's own relay attributes. `interruptible` defaults to none so the
// bridge's speech cannot cut this side's TTS off mid-utterance — one of the
// observations is what happens when that is loosened.
let attrOverrides: Record<string, string> = {};

function callTwiml(): string {
  const attrs: Record<string, string> = {
    url: RELAY_URL,
    transcriptionProvider: "Deepgram",
    speechModel: "flux",
    dtmfDetection: "true",
    interruptible: "none",
    reportInputDuringAgentSpeech: "any",
    events: "speaker-events tokens-played",
    ...attrOverrides,
  };
  const rendered = Object.entries(attrs)
    .filter(([, v]) => v !== "")
    .map(([k, v]) => `${k}="${escapeXml(v)}"`)
    .join(" ");
  return `<?xml version="1.0" encoding="UTF-8"?><Response><Connect action="${BASE_URL}${PREFIX}/action"><ConversationRelay ${rendered}/></Connect></Response>`;
}

async function placeCall(opts: { pin?: "dial" | "dial-late" | "none"; from?: string; hash?: boolean }): Promise<Record<string, unknown>> {
  const pinMode = opts.pin ?? "dial";
  if (pinMode !== "none" && PIN === undefined) return { error: "THICKET_PHONE_PIN not set" };
  // The PIN is exactly eight digits, so the engine completes without the `#`;
  // hash:false keys the dial string without it — the shape that does not barge
  // in on the hello.
  const suffix = opts.hash === false ? "" : "#";
  const body = new URLSearchParams({
    To: NUMBER,
    From: opts.from ?? NUMBER,
    Twiml: callTwiml(),
    StatusCallback: `${BASE_URL}${PREFIX}/status`,
    StatusCallbackMethod: "POST",
    ...(pinMode === "none" ? {} : { SendDigits: (pinMode === "dial-late" ? "wwwwwwww" : "ww") + PIN + suffix }),
  });
  for (const ev of ["initiated", "ringing", "answered", "completed"]) body.append("StatusCallbackEvent", ev);
  const res = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${ACCOUNT}/Calls.json`, {
    method: "POST",
    headers: { authorization: "Basic " + Buffer.from(`${KEY}:${SECRET}`).toString("base64") },
    body,
  });
  const json = (await res.json()) as Record<string, unknown>;
  if (!res.ok) {
    record(undefined, { dir: "rest", createCall: false, status: res.status, code: json.code, message: json.message });
    return { error: json.code, message: json.message };
  }
  restSid = String(json.sid);
  record(restSid, { dir: "rest", createCall: true, pin: pinMode, digitCount: pinMode === "none" ? 0 : (PIN?.length ?? 0) + suffix.length, sid: restSid });
  if (pinMode !== "none") note("keyed", `post-dial: ${(PIN ?? "").length} digits${suffix === "#" ? " and #" : ""}`);
  return { sid: restSid, status: json.status };
}

async function restHangup(): Promise<Record<string, unknown>> {
  const sid = current?.callSid ?? restSid;
  if (!sid) return { error: "no call" };
  const res = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${ACCOUNT}/Calls/${sid}.json`, {
    method: "POST",
    headers: { authorization: "Basic " + Buffer.from(`${KEY}:${SECRET}`).toString("base64") },
    body: new URLSearchParams({ Status: "completed" }),
  });
  record(sid, { dir: "rest", updateStatus: "completed", ok: res.ok, status: res.status });
  return { ok: res.ok };
}

// ---------------------------------------------------------------- outbound frames

function send(call: Call, frame: Record<string, unknown>): void {
  record(call.callSid, { dir: "out", frame });
  call.ws.send(JSON.stringify(frame));
}

function speak(call: Call, text: string, opts: { preemptible?: boolean } = {}): void {
  note("said", text);
  const words = text.split(/\s+/).filter(Boolean);
  words.forEach((w, i) => {
    send(call, {
      type: "text",
      token: (i === 0 ? "" : " ") + w,
      last: i === words.length - 1,
      ...(opts.preemptible ? { preemptible: true } : {}),
    });
  });
}

// ---------------------------------------------------------------- inbound frames

function onFrame(ws: ServerWebSocket<Conn>, raw: string): void {
  let frame: Record<string, unknown>;
  try {
    frame = JSON.parse(raw);
  } catch {
    record(ws.data.callSid, { dir: "in", unparsable: raw });
    return;
  }
  const type = String(frame.type);

  if (type === "setup") {
    const callSid = String(frame.callSid);
    ws.data.callSid = callSid;
    current = { callSid, ws, setupAt: Date.now() };
    for (const e of ws.data.buffered) record(callSid, e);
    ws.data.buffered = [];
    record(callSid, { dir: "in", frame });
    note("event", `setup ${callSid}`);
    return;
  }

  const call = ws.data.callSid ? current : undefined;
  if (!call) {
    ws.data.buffered.push({ dir: "in", frame });
    return;
  }
  record(call.callSid, { dir: "in", frame });

  switch (type) {
    case "prompt":
      // The far end's speech, transcribed on this leg. Only finals matter here;
      // partialPrompts is left off.
      if (frame.last === true) note("heard", String(frame.voicePrompt ?? ""));
      return;
    case "interrupt":
      note("event", `interrupted after: ${String(frame.utteranceUntilInterrupt ?? "")}`);
      return;
    case "error":
      note("event", `relay error: ${String(frame.description ?? "")}`);
      return;
    default:
      return;
  }
}

// ---------------------------------------------------------------- public server

function isRelayPath(pathname: string): boolean {
  return pathname === `${PREFIX}/relay/${RELAY_SECRET}` || pathname === `/relay/${RELAY_SECRET}`;
}

async function handlePublic(req: Request, server: ReturnType<typeof Bun.serve>): Promise<Response> {
  const url = new URL(req.url);
  const path = url.pathname;

  if (isRelayPath(path)) {
    const header = req.headers.get("x-twilio-signature");
    const id = randomBytes(4).toString("hex");
    const entry: Entry = {
      dir: "ws",
      event: "handshake",
      id,
      path,
      signaturePresent: header !== null,
      signatureMatched: signatureCandidates(req, header),
    };
    const ok = server.upgrade(req, { data: { id, buffered: [entry] } satisfies Conn });
    if (ok) return new Response(null);
    record(undefined, { ...entry, upgradeFailed: true });
    return new Response("upgrade failed", { status: 400 });
  }

  if (req.method !== "POST") {
    record(undefined, { dir: "http", path, method: req.method, status: 404, ua: req.headers.get("user-agent") });
    return new Response("not found", { status: 404 });
  }

  const params = new URLSearchParams(await req.text());
  const form = Object.fromEntries(params.entries());
  const callSid = form.CallSid;

  if (path.endsWith("/action")) {
    record(callSid, { dir: "http", path, form });
    note("event", `action: ${String(form.SessionStatus ?? "")} ${String(form.ErrorCode ?? "")}`.trim());
    return new Response(`<?xml version="1.0" encoding="UTF-8"?><Response><Hangup/></Response>`, {
      headers: { "content-type": "text/xml" },
    });
  }
  if (path.endsWith("/status")) {
    record(callSid, { dir: "http", path, callStatus: form.CallStatus, direction: form.Direction });
    return new Response(null, { status: 204 });
  }
  record(callSid, { dir: "http", path, unexpected: true });
  return new Response("not found", { status: 404 });
}

const publicServer = Bun.serve<Conn>({
  hostname: "127.0.0.1",
  port: PUBLIC_PORT,
  fetch: handlePublic,
  websocket: {
    open(ws) {
      ws.data.buffered.push({ dir: "ws", event: "open", id: ws.data.id });
    },
    message(ws, message) {
      onFrame(ws, typeof message === "string" ? message : Buffer.from(message).toString("utf8"));
    },
    close(ws, code, reason) {
      record(ws.data.callSid, {
        dir: "ws",
        event: "close",
        code,
        reason,
        sinceSetupMs: current && ws.data.callSid === current.callSid ? Date.now() - current.setupAt : undefined,
      });
      if (current && ws.data.callSid === current.callSid) current = undefined;
    },
  },
});

// ---------------------------------------------------------------- control server

async function handleControl(req: Request): Promise<Response> {
  if (req.method !== "POST") {
    return Response.json({
      current: current ? { callSid: current.callSid, sinceSetupMs: Date.now() - current.setupAt } : null,
      restSid,
      relayUrl: RELAY_URL,
      attrOverrides,
      transcript,
      recordings: RECORDINGS,
    });
  }
  const body = (await req.json()) as Record<string, unknown>;
  const cmd = String(body.cmd);
  switch (cmd) {
    case "call":
      return Response.json(
        await placeCall({
          pin: body.pin as "dial" | "dial-late" | "none" | undefined,
          from: body.from as string | undefined,
          hash: body.hash as boolean | undefined,
        }),
      );
    case "attrs":
      attrOverrides = (body.attrs as Record<string, string>) ?? {};
      return Response.json({ attrOverrides });
    case "rest-hangup":
      return Response.json(await restHangup());
    case "clear":
      transcript.length = 0;
      return Response.json({ ok: true });
  }
  if (!current) return Response.json({ error: "no current call" }, { status: 409 });
  switch (cmd) {
    case "say":
      speak(current, String(body.text), { preemptible: body.preemptible === true });
      return Response.json({ ok: true });
    case "pin": {
      if (PIN === undefined) return Response.json({ error: "THICKET_PHONE_PIN not set" }, { status: 400 });
      const suffix = body.hash === false ? "" : "#";
      record(current.callSid, { dir: "out", frame: { type: "sendDigits", digitCount: PIN.length + suffix.length } });
      note("keyed", `${PIN.length} digits${suffix === "#" ? " and #" : ""}`);
      current.ws.send(JSON.stringify({ type: "sendDigits", digits: PIN + suffix }));
      return Response.json({ ok: true });
    }
    case "digits":
      note("keyed", String(body.digits));
      send(current, { type: "sendDigits", digits: String(body.digits ?? "") });
      return Response.json({ ok: true });
    case "end":
      send(current, { type: "end", handoffData: JSON.stringify({ reason: "operator-spike" }) });
      return Response.json({ ok: true });
    default:
      return Response.json({ error: `unknown cmd ${cmd}` }, { status: 400 });
  }
}

const controlServer = Bun.serve({ hostname: "127.0.0.1", port: CONTROL_PORT, fetch: handleControl });

console.log(
  JSON.stringify({
    listening: { public: publicServer.port, control: controlServer.port },
    relayUrl: RELAY_URL,
    recordings: RECORDINGS,
  }),
);
